const data = [
    {
        img:"../inception.jpg",
        title:"tytuł",
        ratings:"5"
    },
    {
        img:"./src/moviePosters/",
        title:"tytuł",
        ratings:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },

]
export default data;
